name: darazscrapper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3' # On wednesday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@main # checkout the repository content

      - name: setup python
        uses: actions/setup-python@main
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Daraz web scraper
        run: |
          cd /daraz_scraper 
          scrapy crawl daraz -o output.json
